### ISSUE TITLE
Highlight the tag

### ISSUE THREAD

**Issue by vinu-ganesan** [acoti/articulate.js#8]
Hi,

Thank you for the useful plugin. How can I highlight an element when speaking?

Thanks!

**Comment by acoti** [comment]
Not in the way in which the plugin is set up. With articulate.js, all the words that the user selects with the jQuery command are gathered into one long string and then spoken by the browser. No real way, I don't think, to then go word by word and highlight appropriately.

**Comment by vinu-ganesan** [comment]
Thanks for your reply :+1:
